#!/usr/bin/env python

import requests
import tarfile
import sys
import configparser
import shutil
import os
import progressbar

def download_file(url, destination):
	try:
		size = requests.get(url, stream=True).headers['Content-length']
		dlprog = progressbar.ProgressBar(maxval=int(size)//8192+1)
		with requests.get(url, stream=True) as response:
			response.raise_for_status()
			with open(destination, 'wb') as f:
				test = 0
				for chunk in response.iter_content(chunk_size=8192):
					test += 1
					f.write(chunk)
					dlprog.update(test)
		print("Package Downloaded")
	except requests.exceptions.RequestException as e:
			print("Error:", e)
try:
	test = sys.argv[1]
except IndexError:
	print("""mic 0.3.7

Usage:
install: installs a package
install-local: installs a package from a local file
build: makes a package
remove: removed a package
update: removes and reinstalls a package""")
	exit()

def ifdb(pac):
	global target_dir
	if (sys.argv[2] == "-L"):
		target_dir = sys.argv[3]
	else:
		target_dir = '/'
	if (os.path.exists(target_dir + "etc/mic/") != True):
		os.mkdir(target_dir + "etc/mic/")
	if (os.path.exists(target_dir + "etc/mic/pacdb.ini") != True):
		skjss = open(target_dir + "etc/mic/pacdb.ini", "w")
	global pacdb
	pacdb = configparser.ConfigParser()
	pacdb.read(target_dir + "etc/mic/pacdb.ini")
	if (pac in pacdb):
		print("Package Already Installed")
		return True
	else:
		return False
	
def download(pac):
	print("Downloading Package " + pac + "...")
	download_file("https://micos.paxtonpenguin.com/packages/" + pac + "/" + pac + "-current.mic", "/tmp/" + pac + ".mic")

def extract(badpac):
	global tar
	global pac
	if ".mic" in badpac:
		tar = tarfile.open(badpac, "r")
		pac = badpac.replace(".mic", "")
	else:
		tar = tarfile.open("/tmp/" + badpac + ".mic", "r")
		pac = badpac
	tar.extractall("/tmp/")

def install(badpac):
	global config
	config = configparser.ConfigParser()
	config.read("/tmp/" + pac + "/mic.ini")
	try:
		zdjkfnefn = config['deps']
		print("Getting Dependencies...")
		for key in config['deps']:
			download(key)
			install(key)
	except:
		print("Installing " + badpac + "...")
	global source_dir
	global file_names
	global bar
	source_dir = "/tmp/" + pac + "/root/"
	file_names = os.listdir(source_dir)
	bar = progressbar.ProgressBar(maxval=len(file_names))
	for file_name in file_names:
		try:
			shutil.move(os.path.join(source_dir, file_name), target_dir)
			pacdb[pac + ".rm"] = {}
			pacdb[pac + ".rm"][target_dir + file_name] = ""
			with open(target_dir + 'etc/mic/pacdb.ini', 'w') as configfile:
				pacdb.write(configfile)
				bar.update(file_names.index(file_name))
		except shutil.Error:
			print("skipping file (good)")
	try:
		if ('systemd' in config["post-install"]):
			os.system("systemctl enable " + config["post-install"]["systemd"])
			os.system("systemctl run " + config["post-install"]["systemd"])
		if ('cmd' in config["post-install"]):
			os.system(config["post-install"]["cmd"])
		print("Installation Complete")
	except:
		print("Installation Complete")

def adddb(pac):
	config = configparser.ConfigParser()
	config.read("/tmp/" + pac + "/mic.ini")
	pacdb = configparser.ConfigParser()
	pacdb.read(target_dir + "etc/mic/pacdb.ini")
	pacdb[pac] = {"ver": config["package"]["ver"]}
	with open(target_dir + 'mic/mic/pacdb.ini', 'w') as configfile:
		pacdb.write(configfile)

if (sys.argv[1] == "install"):
	if os.geteuid() != 0:
		exit("you need to run this as root/sudo")
	if sys.argv[2] == "-L":
			argin = sys.argv[4:]
	else:
		argin = sys.argv[2:]
	for arg in argin:
		if ifdb(arg) == True:
			continue
			print("the hell")
		download(arg)
		extract(arg)
		install(arg)
		adddb(arg)

if (sys.argv[1] == "install-local"):
	ifdb(sys.argv[2])
	if os.geteuid() != 0:
		exit("you need to run this as root/sudo")
	extract(sys.argv[2])
	install(sys.argv[2])
	if ".mic" in sys.argv[2]:
		pac = sys.argv[2].replace(".mic", "")
	else:
		pac = sys.argv[2]
	adddb(pac)

if (sys.argv[1] == "build"):
	pac_d = input("Directory of Package Contents: ")
	if (os.path.isfile(pac_d + "/mic.ini") == False):
		config = configparser.ConfigParser()
		pac_name = input("Name of Package: ")
		pac_ver = input("Package Version: ")
		pac_pin = input("Does you package need post-install stuff? [y/n]: ")
		if (pac_pin == "y" or pac_pin == "Y"): 
			pac_sysd = input("Systemd service name [enter to skip]: ")

		config["package"] = {"name": pac_name, "ver": pac_ver}
		config["post-install"] = {}
		if pac_sysd != "":
			config["post-install"]["systemd"] = pac_sysd
		
		with open(pac_d + "/mic.ini", 'w') as configfile:
			config.write(configfile)
		
	config = configparser.ConfigParser()
	config.read(pac_d + '/mic.ini')
	pac_name = config["package"]["name"]
	tar = tarfile.open(pac_name + ".mic", 'w')
	tar.add(pac_d)
	tar.close()

if (sys.argv[1] == "remove"):
	if os.geteuid() != 0:
		exit("you need to run this as root/sudo")
	if (sys.argv[2] == "-L"):
		target_dir = sys.argv[3]
	else:
		target_dir = '/'
	pacdb = configparser.ConfigParser()
	pacdb.read(target_dir + "etc/mic/pacdb.ini")
	for arg in sys.argv[2:]:
		for key in pacdb[arg + ".rm"]:
			os.system("rm -rf " + key)
	with open(target_dir + "etc/mic/pacdb.ini", "r") as f:
		p.readfp(f)
	for arg in sys.argv[2:]:
		p.removesection(arg)
		p.removesection(arg + ".rm") 

if (sys.argv[1] == "update"):
	if os.geteuid() != 0:
		exit("you need to run this as root/sudo")
	pacdb = configparser.ConfigParser()
	pacdb.read(target_dir + "etc/mic/pacdb.ini")
	for arg in sys.argv[2:]:
		extract(arg)
		config = configparser.ConfigParser()
		config.read("/tmp/" + pac + "/mic.ini")
		if (config["package"]["ver"] == pacdb[arg]["ver"]):
			exit("no updates")
		for key in pacdb[arg + ".rm"]:
			os.system("rm -rf " + key)
	with open(target_dir + "etc/mic/pacdb.ini", "r") as f:
		p.readfp(f)
	for arg in sys.argv[2:]:
		p.removesection(arg)
		p.removesection(arg + ".rm") 
	download(arg)
	install(arg)
	adddb(arg)
